sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: lq0OnJHgAVPncc7iPMFURr5WHDcue76DOxzghWyYNB1NFziyAvyKuUCVaw9elODuDlvE/3uKhBBEKevsTX0Td++jTU/lnSANxHRaQ6tQ1TTupJhYsdnbfK8CyZ+ZCMb+Sfqa9TiqmgRcDjHLQGZCDL5LvN8ouK40rCMZWW4mBf7Dlg4e2We4Xu1+Kib+Boz5i7If45KpztQ3p/rnozM2+n9FaDRPcexz8lc1KzGdamkCb/2xLq2vYq+KK6wnwceIKQKRvwoN62yL4stBuf6SuHSNYw4JyJIffVSfmgF+c/lxVMSB1KbAqpw2/KHl3ukA1osyJh/kgV754/C+9260f4ugI3BYqM1UrN5sGnHt1Gd3ZFiYpQjstF4D9+ClWTH6+uJ7FcS261CTKGcEGgTI7lka8ZAW6LiZP6z7ss7j58YqEjH+MEwzE6cf9nTIf7LB63abca103UYPlkM24u7Vz8ivOrNuzCIENAPVQFnEH6lsSy1bDHmdWwNkcW1q4Uwh5/sthvZBz8aU5tCtv4ch83ZChFHQBvzEfPZVci7ii/dZPsjM/6RbcVNCTt23D7s3BNk51A3aVi9GPVzWe/NgSLVyylz1JcHJ6vPeDaKyZ2xuF8fi+okIyGxRvizpkaedSbQRC8PtquqI8Pii6vO2Zg9K89iwxp1ZOCissHObZcY=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Plays---First-Series_5055
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy